services:
  db:
    build:
      context: ./docker_db
      dockerfile: Dockerfile
    ports:
      - 3308:3306
    volumes:
      - ./docker_db/store:/var/lib/mysql
    networks:
      - container_network

  backend:
    build:
      context: ./docker_backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/shop?useSSL=false&serverTimeZone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_DRIVER: com.mariadb.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1005
    networks:
      - container_network

  frontend:
    build:
      context: ./docker_frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - container_network

networks:
  container_network:

